- name: Including the normal Nvidia driver tasks
  include_tasks: Fedora_nvidia_main.yml
  when: not nvidia_use_bumblebee

- name: Including the Nvidia Primus/Bumblebee tasks
  include_tasks: Fedora_nvidia_bumblebee.yml
  when: nvidia_use_bumblebee

- name: Force update the Nvidia kernel module
  command: akmods --force
