- set_fact:
    nvidia_packages:
     - akmod-nvidia
     - nvidia-kmod-common
     - xorg-x11-drv-nvidia
     - xorg-x11-drv-nvidia-kmodsrc
     - xorg-x11-drv-nvidia-libs.i686
     - xorg-x11-drv-nvidia-libs.x86_64

- name: Installing the Fedora workstaiton repositories
  dnf:
    name: fedora-workstation-repositories
    state: latest

- name: Enabling the Nvidia repository
  lineinfile:
    path: /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
    regexp: "^enabled"
    line: "enabled=1"

- name: Installing the Nvidia driver packages
  dnf:
    name: "{{ item }}"
    state: latest
    enablerepo: rpmfusion-nonfree-nvidia-driver
  loop: "{{ nvidia_packages }}"

- name: Including the Bumblebee tasks
  include_tasks: Fedora_nvidia_bumblebee.yml
  when: nvidia_use_bumblebee

- name: Force update the Nvidia kernel module
  command: akmods --force
