# Following the instructions from:
# http://fedoraproject.org/wiki/Bumblebee
- name: Installing the Fedora Nvidia repository
  shell: dnf -y config-manager --add-repo=https://negativo17.org/repos/fedora-nvidia.repo

- name: Installing Nvidia packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia-driver
    - kernel-devel
    - akmod-nvidia
    - dkms
    - acpi

- name: Installing the Bumblebee repository
  shell: dnf -y copr enable chenxiaolong/bumblebee

- name: Installing Bumblebee
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - akmod-bbswitch
    - bumblebee
    - primus

- name: Allowing a user to use the "optirun" and "primusrun" commands
  user:
    name: "{{ gpu_driver_bumblebee_user }}"
    groups: bumblebee
    append: yes
  when: bumblebee_user is defined

- name: Enabling Bumblebee
  systemd:
    name: bumblebeed
    enabled: yes

- name: Disallowing Nvidia to fallback to Nouveau
  systemd:
    name: nvidia-fallback
    masked: yes
    enabled: no
